name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt --verbose
        pip list  # Debug: List installed packages

    - name: Debug Environment
      run: |
        pwd
        ls -la
        python --version
        which python

    - name: Sync with Hugging Face Space
      env:
        HUGGING_FACE_API_TOKEN: ${{ secrets.HUGGING_FACE_API_TOKEN }}
      run: |
        echo "Starting sync with Hugging Face Space..."
        
        # Clone the space repository
        git clone "https://${{ secrets.HUGGING_FACE_API_TOKEN }}@huggingface.co/srabhishek/Pathogenevolutionexplorer.git" space_repo || exit 1
        
        # Debug: List files before sync
        echo "Files before sync:"
        ls -la space_repo/
        
        # Sync files
        rsync -av --exclude '.git' --exclude 'venv' --stats . space_repo/
        
        # Debug: List files after sync
        echo "Files after sync:"
        ls -la space_repo/
        
        # Configure git and push changes
        cd space_repo
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git status  # Debug: Show git status
        git commit -m "Sync changes from GitHub repository [skip ci]"
        git push || { echo "Push failed"; exit 1; }
        
        echo "Sync completed successfully"
