name: Sync to Hugging Face Space
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        
    - name: Sync with Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HUGGING_FACE_API_TOKEN }}
      run: |
        echo "Cloning Hugging Face repository..."
        # Configure Git to use HTTPS with credentials in the URL
        git config --global credential.helper store
        echo "https://oauth2:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
        git clone "https://oauth2:${HF_TOKEN}@huggingface.co/spaces/srabhishek/Pathogenevolutionexplorer.git" space_repo
        cd space_repo
        rsync -av --exclude '.git' ../ ./
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync changes from GitHub repository"
        git push origin main
