name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt --verbose
        pip list  # Debug: List installed packages

    - name: Debug Environment
      run: |
        pwd
        ls -la
        python --version
        which python

    - name: Sync with Hugging Face Space
      run: |
        echo "Cloning Hugging Face repository..."
        git config --global credential.helper store
        git clone https://huggingface.co/spaces/srabhishek/Pathogenevolutionexplorer space_repo
        cd space_repo
        rsync -av --exclude '.git' ../ ./
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync changes from GitHub repository [skip ci]"
        git push https://huggingface.co/spaces/srabhishek/Pathogenevolutionexplorer
      env:
        GIT_LFS_SKIP_SMUDGE: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HF_TOKEN: ${{ secrets.HUGGING_FACE_API_TOKEN }}